### PR TITLE
cm: Remove garbage from sepolicy

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by r-matlock** [comment]
What does this exactly do?

**Comment by ghost** [comment]
it causes the rules to be invalid

**Comment by r-matlock** [comment]
Have you tested / are you sure about this? If you are 100% sure that this works, I'll merge it.

**Comment by ghost** [comment]
yeah

**Comment by ZdrowyGosciu** [comment]
http://review.cyanogenmod.org/#/c/142588/

**Comment by r-matlock** [comment]
Thanks @ZdrowyGosciu

**Pull request closed without merging**
